version: "3"
services:
#  app:
#    container_name: app
#    build: .
#    volumes:
#    - .:/app
#    entrypoint: elixir -v
  app2:
    container_name: app2
    build: .
    ports:
    - "80:${PORT}"
    environment:
      PORT: ${PORT}
    volumes:
    - .:/app
#    entrypoint: mix phoenix.new /app --app penr_oz_elixir --no-brunch
    entrypoint: mix phoenix.server